#!/usr/bin/env bash
# 단일 규칙 파일 /etc/udev/rules.d/99-bushub-serial.rules 를 매 설치마다 통째로 덮어씁니다.
#
# 기본(usb485): 01 DDC 프로브 fragment + 02 PC fragment → bushub-controller + bushub-people-counter-N
# --apc-only(integrated): 02 PC fragment 만 → bushub-people-counter-N (Modbus는 호스트 /dev/ttyS0)
#
# 옵션:
#   --strict     링크 검증 실패 시 비정상 종료(마법사·CI)
#   --apc-only   컨트롤러 fragment 없이 APC 규칙만 설치
#
set -euo pipefail

STRICT=0
APC_ONLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT=1
      shift
      ;;
    --apc-only)
      APC_ONLY=1
      shift
      ;;
    -h|--help)
      echo "사용법: $0 [--strict] [--apc-only]"
      echo "  --strict     필수 심볼릭 링크가 없으면 exit 1"
      echo "  --apc-only   PeopleCounter USB 규칙만 (integrated). 01 프로브 생략 가능."
      exit 0
      ;;
    *)
      echo "알 수 없는 인자: $1" >&2
      echo "도움말: $0 --help" >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VERIFY_SCRIPT="$SCRIPT_DIR/04-verify-bushub-serial.sh"

TMP_DIR="/tmp/bushub-udev-rules"
CONTROLLER_FRAGMENT="$TMP_DIR/99-bushub-serial-controller.fragment"
# apc-only(integrated): 미설정 시 0(규칙만 비우기 등). usb485 전체: 미설정 시 1(기존 호환)
if [ "$APC_ONLY" -eq 1 ]; then
  PEOPLE_COUNTER_COUNT="${PEOPLE_COUNTER_COUNT:-0}"
else
  PEOPLE_COUNTER_COUNT="${PEOPLE_COUNTER_COUNT:-1}"
fi

RULE_FILE="/etc/udev/rules.d/99-bushub-serial.rules"

if ! [[ "$PEOPLE_COUNTER_COUNT" =~ ^[0-3]$ ]]; then
  echo "❌ PEOPLE_COUNTER_COUNT는 0~3 정수여야 합니다. 현재: $PEOPLE_COUNTER_COUNT" >&2
  exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "관리자 권한이 필요합니다. sudo 로 실행하세요."
  exit 1
fi

if [ "$APC_ONLY" -eq 0 ]; then
  if [ ! -f "$CONTROLLER_FRAGMENT" ]; then
    echo "❌ 컨트롤러 fragment가 없습니다: $CONTROLLER_FRAGMENT"
    echo "   ./usb485/01-probe-ddc-bushub-usb-serial.sh 부터 실행하세요."
    exit 1
  fi
  if [ ! -s "$CONTROLLER_FRAGMENT" ]; then
    echo "❌ 컨트롤러 fragment 파일이 없거나 비어있습니다: $CONTROLLER_FRAGMENT"
    exit 1
  fi
fi

if [ "$PEOPLE_COUNTER_COUNT" -ge 1 ]; then
  for i in $(seq 1 "$PEOPLE_COUNTER_COUNT"); do
    pc_frag="$TMP_DIR/99-bushub-serial-people-counter-$i.fragment"
    if [ ! -s "$pc_frag" ]; then
      echo "❌ 피플카운터 fragment가 없거나 비어있습니다: $pc_frag"
      echo "   ./common/02-probe-pc-bushub-usb-serial.sh --index $i 부터 실행하세요."
      exit 1
    fi
  done
fi

echo "✅ fragment 존재 확인 완료 (PEOPLE_COUNTER_COUNT=$PEOPLE_COUNTER_COUNT, apc_only=$APC_ONLY)"

if [ -f "$RULE_FILE" ]; then
  TS="$(date +%Y%m%d-%H%M%S)"
  BACKUP_FILE="${RULE_FILE}.bak.${TS}"
  echo "🔒 기존 udev rules 백업 중: $RULE_FILE -> $BACKUP_FILE"
  cp -f "$RULE_FILE" "$BACKUP_FILE"
  echo "✅ 백업 완료"
fi

echo "📌 udev rules 설치 중: $RULE_FILE"
if [ "$APC_ONLY" -eq 1 ]; then
  cat > "$RULE_FILE" <<EOF
# Generated by common/03-install-bushub-serial.sh --apc-only ($(date -Is))
# Modbus는 호스트 /dev/ttyS0 (integrated). 이 파일은 PeopleCounter(APC USB)만 정의합니다.
# - /dev/bushub-people-counter-1..N (PEOPLE_COUNTER_COUNT>=1)
#
EOF
else
  cat > "$RULE_FILE" <<EOF
# Generated by 01/02 probe scripts ($(date -Is))
# - /dev/bushub-controller
# - /dev/bushub-people-counter-1..N
#
# Controller rule:
$(cat "$CONTROLLER_FRAGMENT")
EOF
fi

if [ "$PEOPLE_COUNTER_COUNT" -ge 1 ]; then
  {
    echo "#"
    echo "# PeopleCounter rules:"
    for i in $(seq 1 "$PEOPLE_COUNTER_COUNT"); do
      echo "# - /dev/bushub-people-counter-$i"
      cat "$TMP_DIR/99-bushub-serial-people-counter-$i.fragment"
      echo ""
    done
  } >> "$RULE_FILE"
fi

echo "🔄 udev rules reload"
udevadm control --reload-rules

echo "⚡ udev trigger (tty 대상)"
udevadm trigger --subsystem-match=tty || true

echo "⏱️ udev settle"
udevadm settle || true
sleep 1

echo ""
echo "🔍 링크 확인 (04-verify-bushub-serial.sh)"
VERIFY_ARGS=()
if [ "$APC_ONLY" -eq 1 ]; then
  VERIFY_ARGS+=(--apc-only)
fi
if [ ! -f "$VERIFY_SCRIPT" ]; then
  echo "⚠️  $VERIFY_SCRIPT 없음 — 수동으로 링크를 확인하세요."
else
  bash "$VERIFY_SCRIPT" "${VERIFY_ARGS[@]}"
fi

controller_ok=0
people_ok=0

if [ "$APC_ONLY" -eq 1 ]; then
  controller_ok=1
else
  [ -L /dev/bushub-controller ] && controller_ok=1
fi

if [ "$PEOPLE_COUNTER_COUNT" -eq 0 ]; then
  people_ok=1
else
  all_ok=1
  for i in $(seq 1 "$PEOPLE_COUNTER_COUNT"); do
    [ -L "/dev/bushub-people-counter-$i" ] || all_ok=0
  done
  [ "$all_ok" -eq 1 ] && people_ok=1
fi

if [ "$controller_ok" -eq 1 ] && [ "$people_ok" -eq 1 ]; then
  echo ""
  echo "🎉 udev 설치 완료"
  exit 0
fi

echo ""
echo "⚠️  규칙은 설치되었으나, 위에서 일부 링크가 없습니다."
echo "   udev trigger 직후에는 생성되지 않을 수 있습니다. 아래를 순서대로 확인하세요."
echo ""
if [ "$APC_ONLY" -eq 0 ]; then
  echo "   • 두 규칙은 01·02 프로브 당시의 USB 포트(KERNELS)에 맞춰집니다."
  echo "     다른 포트·허브에 꽂았다면 01 → 02 → (이 스크립트) 를 다시 실행하세요."
else
  echo "   • APC 규칙은 02 프로브 당시의 USB 포트(KERNELS)에 맞춰집니다."
  echo "     다른 포트에 꽂았다면 02 → (이 스크립트) 를 다시 실행하세요."
fi
echo "   • USB를 뽑았다가 다시 꽂은 뒤:"
echo "       sudo udevadm trigger --subsystem-match=tty && sudo udevadm settle"
if [ "$APC_ONLY" -eq 1 ]; then
  echo "   • 재확인: bash $VERIFY_SCRIPT --apc-only"
else
  echo "   • 재확인: bash $VERIFY_SCRIPT"
fi
if [ "$STRICT" -eq 1 ]; then
  echo ""
  if [ "$APC_ONLY" -eq 1 ]; then
    echo "❌ --strict: PeopleCounter 심볼릭 링크가 모두 생성되지 않아 비정상 종료합니다."
  else
    echo "❌ --strict: bushub-controller 및 PeopleCounter 심볼릭 링크가 모두 생성되지 않아 비정상 종료합니다."
  fi
  exit 1
fi
exit 0
