// 장비별 설정항목 상세 명세

export const deviceSpecs = [
  {
    deviceId: 'd011',
    deviceType: 'lighting',
    deviceName: '조명',
    styles: {
      icon: 'Lightbulb',
      color: 'text-yellow-500',
      bgColor: 'bg-yellow-50',
      cardColor: 'text-yellow-700',
      cardBg: 'bg-yellow-100',
      cardIconColor: 'text-yellow-600',
    },
    commands: [
      {
        key: 'power',
        label: '전원',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_POWER',
          set: 'SET_POWER',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '켜짐', false: '꺼짐' },
        defaultValue: false,
      },
      {
        key: 'start_time_1',
        label: '시작시간1',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간1',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'start_time_2',
        label: '시작시간2',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_2',
          set: 'SET_START_TIME_2',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '18:00',
      },
      {
        key: 'end_time_2',
        label: '종료시간2',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_2',
          set: 'SET_END_TIME_2',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '06:00',
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
    ],
  },
  {
    deviceId: 'd021',
    deviceType: 'cooler',
    deviceName: '냉난방기',
    styles: {
      icon: 'Fan',
      color: 'text-blue-500',
      bgColor: 'bg-blue-50',
      cardColor: 'text-blue-700',
      cardBg: 'bg-blue-100',
      cardIconColor: 'text-blue-600',
    },
    commands: [
      {
        key: 'power',
        label: '전원',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_POWER',
          set: 'SET_POWER',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '켜짐', false: '꺼짐' },
        defaultValue: false,
      },
      {
        key: 'start_time_1',
        label: '시작시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'mode',
        label: '모드',
        type: 'int',
        get: true,
        set: true,
        action: {
          get: 'GET_MODE',
          set: 'SET_MODE',
        },
        min: 0,
        max: 4,
        unit: null,
        options: [0, 1, 2, 3, 4],
        optionLabels: { 0: '냉방', 1: '제습', 2: '송풍', 3: '자동', 4: '난방' },
        defaultValue: 3,
      },
      {
        key: 'summer_cont_temp',
        label: '여름 목표온도',
        type: 'float',
        get: true,
        set: true,
        action: {
          get: 'GET_SUMMER_CONT_TEMP',
          set: 'SET_SUMMER_CONT_TEMP',
        },
        min: 16,
        max: 30,
        unit: '°C',
        options: [],
        defaultValue: 22,
      },
      {
        key: 'winter_cont_temp',
        label: '겨울 목표온도',
        type: 'float',
        get: true,
        set: true,
        action: {
          get: 'GET_WINTER_CONT_TEMP',
          set: 'SET_WINTER_CONT_TEMP',
        },
        min: 16,
        max: 30,
        unit: '°C',
        options: [],
        defaultValue: 22,
      },
      {
        key: 'speed',
        label: '풍량',
        type: 'int',
        get: true,
        set: true,
        action: {
          get: 'GET_SPEED',
          set: 'SET_SPEED',
        },
        min: 1,
        max: 4,
        unit: null,
        options: [1, 2, 3, 4],
        optionLabels: { 1: '약', 2: '중', 3: '강', 4: '자동' },
        defaultValue: 4,
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
      {
        key: 'cur_temp',
        label: '현재온도',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_CUR_TEMP',
        },
        min: -99,
        max: 99,
        unit: '°C',
        options: [],
        defaultValue: 20,
      },
      {
        key: 'alarm',
        label: '알람 상태',
        type: 'int',
        get: true,
        set: false,
        action: {
          get: 'GET_ALARM',
        },
        min: 0,
        max: 255,
        unit: '',
        options: [],
        defaultValue: 0,
      },
    ],
  },
  {
    deviceId: 'd022',
    deviceType: 'exchanger',
    deviceName: '전열교환기',
    styles: {
      icon: 'Activity',
      color: 'text-green-500',
      bgColor: 'bg-green-50',
      cardColor: 'text-green-700',
      cardBg: 'bg-green-100',
      cardIconColor: 'text-green-600',
    },
    commands: [
      {
        key: 'power',
        label: '전원',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_POWER',
          set: 'SET_POWER',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '켜짐', false: '꺼짐' },
        defaultValue: false,
      },
      {
        key: 'start_time_1',
        label: '시작시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'mode',
        label: '운전모드',
        type: 'int',
        get: true,
        set: true,
        action: {
          get: 'GET_MODE',
          set: 'SET_MODE',
        },
        min: 1,
        max: 2,
        unit: null,
        options: [1, 2],
        optionLabels: { 1: '수동', 2: '자동' },
        defaultValue: 2,
      },
      {
        key: 'speed',
        label: '풍량',
        type: 'int',
        get: true,
        set: true,
        action: {
          get: 'GET_SPEED',
          set: 'SET_SPEED',
        },
        min: 1,
        max: 3,
        unit: null,
        options: [1, 2, 3],
        optionLabels: { 1: '약', 2: '중', 3: '강' },
        defaultValue: 2,
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
      {
        key: 'alarm',
        label: '알람 상태',
        type: 'int',
        get: true,
        set: false,
        action: {
          get: 'GET_ALARM',
        },
        min: 0,
        max: 1,
        unit: '',
        options: [1, 0],
        optionLabels: { 1: '이상', 0: '정상' },
      },
    ],
  },
  {
    deviceId: 'd023',
    deviceType: 'aircurtain',
    deviceName: '에어커튼',
    styles: {
      icon: 'Fan',
      color: 'text-cyan-500',
      bgColor: 'bg-cyan-50',
      cardColor: 'text-cyan-700',
      cardBg: 'bg-cyan-100',
      cardIconColor: 'text-cyan-600',
    },
    commands: [
      {
        key: 'power',
        label: '전원',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_POWER',
          set: 'SET_POWER',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '켜짐', false: '꺼짐' },
        defaultValue: false,
      },
      {
        key: 'start_time_1',
        label: '시작시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
    ],
  },
  {
    deviceId: 'd041',
    deviceType: 'bench',
    deviceName: '온열벤치',
    styles: {
      icon: 'Thermometer',
      color: 'text-orange-500',
      bgColor: 'bg-orange-50',
      cardColor: 'text-orange-700',
      cardBg: 'bg-orange-100',
      cardIconColor: 'text-orange-600',
    },
    commands: [
      {
        key: 'power',
        label: '전원',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_POWER',
          set: 'SET_POWER',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '켜짐', false: '꺼짐' },
        defaultValue: false,
      },
      {
        key: 'start_time_1',
        label: '시작시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
    ],
  },
  {
    deviceId: 'd051',
    deviceType: 'door',
    deviceName: '자동문',
    styles: {
      icon: 'DoorOpen',
      color: 'text-gray-500',
      bgColor: 'bg-gray-50',
      cardColor: 'text-gray-700',
      cardBg: 'bg-gray-100',
      cardIconColor: 'text-gray-600',
    },
    commands: [
      {
        key: 'power',
        label: '전원',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_POWER',
          set: 'SET_POWER',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '켜짐', false: '꺼짐' },
        defaultValue: false,
      },
      {
        key: 'start_time_1',
        label: '시작시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
    ],
  },
  {
    deviceId: 'd061',
    deviceType: 'integrated_sensor', //'sensor',
    deviceName: '통합센서',
    styles: {
      icon: 'Activity',
      color: 'text-purple-500',
      bgColor: 'bg-purple-50',
      cardColor: 'text-purple-700',
      cardBg: 'bg-purple-100',
      cardIconColor: 'text-purple-600',
    },
    commands: [
      {
        key: 'pm100',
        label: '미세먼지',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_PM100',
        },
        min: 0,
        max: 1000,
        unit: '㎍/㎥',
        options: [],
      },
      {
        key: 'pm25',
        label: '초미세먼지',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_PM25',
        },
        min: 0,
        max: 1000,
        unit: '㎍/㎥',
        options: [],
      },
      {
        key: 'pm10',
        label: '초초미세먼지',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_PM10',
        },
        min: 0,
        max: 1000,
        unit: '㎍/㎥',
        options: [],
      },
      {
        key: 'co2',
        label: '이산화탄소',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_CO2',
        },
        min: 400,
        max: 10000,
        unit: 'ppm',
        options: [],
      },
      {
        key: 'voc',
        label: '유기화합물',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_VOC',
        },
        min: 0,
        max: 60000,
        unit: 'ppb',
        options: [],
      },
      {
        key: 'hum',
        label: '습도',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_HUM',
        },
        min: 0,
        max: 100,
        unit: '%',
        options: [],
      },
      {
        key: 'temp',
        label: '온도',
        type: 'float',
        get: true,
        set: false,
        action: {
          get: 'GET_TEMP',
        },
        min: -40,
        max: 125,
        unit: '°C',
        options: [],
      },
    ],
  },
  {
    deviceId: 'd081',
    deviceType: 'externalsw',
    deviceName: '자동문외부스위치',
    styles: {
      icon: 'Gauge',
      color: 'text-gray-400',
      bgColor: 'bg-gray-50',
      cardColor: 'text-gray-700',
      cardBg: 'bg-gray-100',
      cardIconColor: 'text-gray-600',
    },
    commands: [
      {
        key: 'start_time_1',
        label: '시작시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_START_TIME_1',
          set: 'SET_START_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '08:00',
      },
      {
        key: 'end_time_1',
        label: '종료시간',
        type: 'string',
        get: true,
        set: true,
        action: {
          get: 'GET_END_TIME_1',
          set: 'SET_END_TIME_1',
        },
        min: '00:00',
        max: '23:59',
        unit: null,
        options: [],
        defaultValue: '22:00',
      },
      {
        key: 'auto',
        label: '자동모드',
        type: 'boolean',
        get: true,
        set: true,
        action: {
          get: 'GET_AUTO',
          set: 'SET_AUTO',
        },
        min: null,
        max: null,
        unit: null,
        options: [true, false],
        optionLabels: { true: '자동', false: '수동' },
        defaultValue: true,
      },
    ],
  },
];
