#!/bin/bash
# udev 규칙을 설치하고 /dev/bushub-controller, /dev/bushub-people-counter 를 생성합니다.
#
# 이 스크립트는 반드시 백업을 수행합니다.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VERIFY_SCRIPT="$SCRIPT_DIR/04-verify-bushub-usb-serial.sh"

TMP_DIR="/tmp/bushub-udev-rules"
CONTROLLER_FRAGMENT="$TMP_DIR/99-bushub-serial-controller.fragment"
PEOPLE_COUNTER_FRAGMENT="$TMP_DIR/99-bushub-serial-people-counter.fragment"

RULE_FILE="/etc/udev/rules.d/99-bushub-serial.rules"

if [ "$(id -u)" -ne 0 ]; then
  echo "관리자 권한이 필요합니다. sudo 로 실행하세요."
  exit 1
fi

if [ ! -f "$CONTROLLER_FRAGMENT" ]; then
  echo "❌ 컨트롤러 fragment가 없습니다: $CONTROLLER_FRAGMENT"
  echo "   ./01-probe-ddc-bushub-usb-serial.sh 부터 실행하세요."
  exit 1
fi

if [ ! -f "$PEOPLE_COUNTER_FRAGMENT" ]; then
  echo "❌ 피플카운터 fragment가 없습니다: $PEOPLE_COUNTER_FRAGMENT"
  echo "   ./02-probe-pc-bushub-usb-serial.sh 부터 실행하세요."
  exit 1
fi

if [ -s "$CONTROLLER_FRAGMENT" ] && [ -s "$PEOPLE_COUNTER_FRAGMENT" ]; then
  echo "✅ fragment 존재 확인 완료"
else
  echo "❌ fragment 파일이 비어있습니다. 내용을 확인하세요."
  exit 1
fi

if [ -f "$RULE_FILE" ]; then
  TS="$(date +%Y%m%d-%H%M%S)"
  BACKUP_FILE="${RULE_FILE}.bak.${TS}"
  echo "🔒 기존 udev rules 백업 중: $RULE_FILE -> $BACKUP_FILE"
  cp -f "$RULE_FILE" "$BACKUP_FILE"
  echo "✅ 백업 완료"
fi

echo "📌 udev rules 설치 중: $RULE_FILE"
cat > "$RULE_FILE" <<EOF
# Generated by 01/02 probe scripts ($(date -Is))
# - /dev/bushub-controller
# - /dev/bushub-people-counter
#
# Controller rule:
$(cat "$CONTROLLER_FRAGMENT")
#
# PeopleCounter rule:
$(cat "$PEOPLE_COUNTER_FRAGMENT")
EOF

echo "🔄 udev rules reload"
udevadm control --reload-rules

echo "⚡ udev trigger (tty 대상)"
udevadm trigger --subsystem-match=tty || true

echo "⏱️ udev settle"
udevadm settle || true

echo ""
echo "🔍 링크 확인 (04-verify-bushub-usb-serial.sh)"
if [ ! -f "$VERIFY_SCRIPT" ]; then
  echo "⚠️  $VERIFY_SCRIPT 없음 — 수동으로 링크를 확인하세요."
else
  # install 은 sudo 로 실행되므로 동일 환경에서 검사
  bash "$VERIFY_SCRIPT"
fi

controller_ok=0
people_ok=0
[ -L /dev/bushub-controller ] && controller_ok=1
[ -L /dev/bushub-people-counter ] && people_ok=1

if [ "$controller_ok" -eq 1 ] && [ "$people_ok" -eq 1 ]; then
  echo ""
  echo "🎉 udev 설치 완료"
  exit 0
fi

echo ""
echo "⚠️  규칙은 설치되었으나, 위에서 일부 링크가 없습니다."
echo "   udev trigger 직후에는 생성되지 않을 수 있습니다. USB를 뽑았다가 다시 꽂거나,"
echo "   해당 장비를 연결한 뒤 ./04-verify-bushub-usb-serial.sh 로 다시 확인하세요."
exit 0
