#!/bin/bash
# udev 규칙을 설치하고 /dev/bushub-controller, /dev/bushub-people-counter 를 생성합니다.
#
# 이 스크립트는 반드시 백업을 수행합니다.
#
set -euo pipefail

TMP_DIR="/tmp/bushub-udev-rules"
CONTROLLER_FRAGMENT="$TMP_DIR/99-bushub-serial-controller.fragment"
PEOPLE_COUNTER_FRAGMENT="$TMP_DIR/99-bushub-serial-people-counter.fragment"

RULE_FILE="/etc/udev/rules.d/99-bushub-serial.rules"

if [ "$(id -u)" -ne 0 ]; then
  echo "관리자 권한이 필요합니다. sudo 로 실행하세요."
  exit 1
fi

if [ ! -f "$CONTROLLER_FRAGMENT" ]; then
  echo "❌ 컨트롤러 fragment가 없습니다: $CONTROLLER_FRAGMENT"
  echo "   ./bushub-usb-serial-controller-probe.sh 부터 실행하세요."
  exit 1
fi

if [ ! -f "$PEOPLE_COUNTER_FRAGMENT" ]; then
  echo "❌ 피플카운터 fragment가 없습니다: $PEOPLE_COUNTER_FRAGMENT"
  echo "   ./bushub-usb-serial-people-counter-probe.sh 부터 실행하세요."
  exit 1
fi

if [ -s "$CONTROLLER_FRAGMENT" ] && [ -s "$PEOPLE_COUNTER_FRAGMENT" ]; then
  echo "✅ fragment 존재 확인 완료"
else
  echo "❌ fragment 파일이 비어있습니다. 내용을 확인하세요."
  exit 1
fi

if [ -f "$RULE_FILE" ]; then
  TS="$(date +%Y%m%d-%H%M%S)"
  BACKUP_FILE="${RULE_FILE}.bak.${TS}"
  echo "🔒 기존 udev rules 백업 중: $RULE_FILE -> $BACKUP_FILE"
  cp -f "$RULE_FILE" "$BACKUP_FILE"
  echo "✅ 백업 완료"
fi

echo "📌 udev rules 설치 중: $RULE_FILE"
cat > "$RULE_FILE" <<EOF
# Generated by bushub-usb-serial-* probes ($(date -Is))
# - /dev/bushub-controller
# - /dev/bushub-people-counter
#
# Controller rule:
$(cat "$CONTROLLER_FRAGMENT")
#
# PeopleCounter rule:
$(cat "$PEOPLE_COUNTER_FRAGMENT")
EOF

echo "🔄 udev rules reload"
udevadm control --reload-rules

echo "⚡ udev trigger (tty 대상)"
udevadm trigger --subsystem-match=tty || true

echo "⏱️ udev settle"
udevadm settle || true

echo "🔍 링크 확인"
if [ -L /dev/bushub-controller ]; then
  echo "✅ /dev/bushub-controller -> $(readlink -f /dev/bushub-controller)"
else
  echo "❌ /dev/bushub-controller 가 생성되지 않았습니다."
  echo "   USB를 뽑았다가 다시 꽂고 ./bushub-usb-serial-verify.sh 를 실행해 보세요."
  exit 1
fi

if [ -L /dev/bushub-people-counter ]; then
  echo "✅ /dev/bushub-people-counter -> $(readlink -f /dev/bushub-people-counter)"
else
  echo "❌ /dev/bushub-people-counter 가 생성되지 않았습니다."
  echo "   USB를 뽑았다가 다시 꽂고 ./bushub-usb-serial-verify.sh 를 실행해 보세요."
  exit 1
fi

echo "🎉 udev 설치 완료"

